Разметка страниц - главная, каталог.
htmlacademy-htmlcss/1897183-sedona-32 pull request #2
Opened 2021-09-29 18:25 UTC by DmitryGladkikh

2021-09-30 13:06 UTC, Dima-Dim requested changes
https://up.htmlacademy.ru/htmlcss/32/criteries#PROJ-02
 katalog - ?

https://up.htmlacademy.ru/htmlcss/32/help/4.5
"Приступать к следующему заданию по тому же проекту не стоит, пока не будет принято предыдущее."

2021-09-30 13:06 UTC, Dima-Dim commented on index.html
> +        <ul class="navigation-list navigation-user">
Это не список, потому что его элементы не однородны.

2021-09-30 13:06 UTC, Dima-Dim commented on index.html
> +        <a class="logo" href="#">Логотип</a>
Начиная отсюда идёт не основаная навигация, которую лучше не включать в тег nav.

2021-09-30 13:06 UTC, Dima-Dim commented on index.html
> +      <h1 class="visually-hidden">Сайт о небошльшом городке Седона</h1>
Для чего нам скрытый заголовок есть явный? Ну и за одно, на странице должен быть только 1 H1.

2021-09-30 13:06 UTC, Dima-Dim commented on index.html
> +        <p class="visually-hidden">Преимущества</p>
Почему p?

2021-09-30 13:06 UTC, Dima-Dim commented on katalog.html
> +              </ul>
Что за списки из одного пункта? :)

2021-09-30 13:06 UTC, Dima-Dim commented on katalog.html
> +                  <h4 class="hotel-card-title">Гостиница</h4>
Это скорее p.

2021-10-03 08:09 UTC, DmitryGladkikh commented on index.html
> +        <a class="logo" href="#">Логотип</a>
Исправил

2021-10-03 08:18 UTC, DmitryGladkikh commented on index.html
> +      <h1 class="visually-hidden">Сайт о небошльшом городке Седона</h1>
Тут я не совсем понял. Там есть явный заголовок, но он векторный. Поэтому пока что тут я решил оставить скрытый заголовок.

2021-10-03 08:22 UTC, DmitryGladkikh commented on index.html
> +        <ul class="navigation-list navigation-user">
Тут я сделал в соответствии с лайвом, там эти пункты сделали списком

2021-10-03 08:29 UTC, DmitryGladkikh commented on index.html
> +        <p class="visually-hidden">Преимущества</p>
Заголовок h2

2021-10-03 08:45 UTC, DmitryGladkikh commented on katalog.html
> +                  <h4 class="hotel-card-title">Гостиница</h4>
Не совсем понял, вместо h2 h3 нужно p?

2021-10-03 08:45 UTC, DmitryGladkikh commented on katalog.html
> +              </ul>
Карточки товара сделал в соответствии с лайвом, там тоже были списки

2021-10-03 12:11 UTC, Dima-Dim commented on index.html
> +      <h1 class="visually-hidden">Сайт о небошльшом городке Седона</h1>
А на 46-ой строке что? Перед `<h2>Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</h2>`

2021-10-03 12:12 UTC, Dima-Dim commented on index.html
> +        <ul class="navigation-list navigation-user">
Хорошо, пусть будет так.

2021-10-03 12:12 UTC, Dima-Dim commented on index.html
> +        <p class="visually-hidden">Преимущества</p>
Да, так будет лучше.

2021-10-03 12:14 UTC, Dima-Dim commented on katalog.html
> +                  <h4 class="hotel-card-title">Гостиница</h4>
`<h3 class="hotel-card-title">Amara Resort & Spa</h3>` можно оставить, а `Гостиница` лучше сделать p.

2021-10-03 12:15 UTC, Dima-Dim commented on katalog.html
> +              </ul>
Были списки из одного элемена? Покаже где, хочу посмотреть на это :)

2021-10-03 15:35 UTC, DmitryGladkikh commented on index.html
> +      <h1 class="visually-hidden">Сайт о небошльшом городке Седона</h1>
Тогда я думаю лучше уберу скрытый совсем.

2021-10-03 15:38 UTC, DmitryGladkikh commented on katalog.html
> +                  <h4 class="hotel-card-title">Гостиница</h4>
Исправил

2021-10-03 15:45 UTC, DmitryGladkikh commented on katalog.html
> +              </ul>
Скорее всего я не понимаю вопрос)

2021-10-03 15:50 UTC, Dima-Dim commented on katalog.html
> +              </ul>
Вопрос очень простой :) Зачем нам списки состоязие из одного пункта?

2021-10-03 17:05 UTC, DmitryGladkikh commented on katalog.html
> +              </ul>
У меня каждый отель обернут в тег ul, возможно не нужно каждый оборачивать, а обернуть всё в общий список? 
<ul>
список всех отелей
</ul>

2021-10-04 05:58 UTC, Dima-Dim commented on katalog.html
> +              </ul>
Да, если от абстракций спустится к конкретике, то да, вопрос в том, зачем каждый отель — это список? Мне интересно понять почем был выбран такой вариант разметки. При этом почему все отели — это не список?

2021-10-04 06:43 UTC, DmitryGladkikh commented on katalog.html
> +              </ul>
Дмитрий, я уже голову сломал) Этот раздел возможно еще разметить тегом br

2021-10-04 08:12 UTC, Dima-Dim commented on katalog.html
> +              </ul>
Сломал голову над чем? :) Я не прошу дать правильный ответ, я лишь хочу узнать почему был выбран именно такой вариант :)

2021-10-04 08:24 UTC, DmitryGladkikh commented on katalog.html
> +              </ul>
В лайве по разметке Андрей сделал карточку товара списком https://up.htmlacademy.ru/profession/frontender/12/htmlcss/demos/5943#27 , ну и я последовал его примеру и сделал этот раздел списком)

2021-10-04 09:39 UTC, Dima-Dim commented on katalog.html
> +              </ul>
Хорошо, но в примере списом являются карточки, а не каждая карточка по отдельности.

2021-10-04 13:57 UTC, DmitryGladkikh commented on katalog.html
> +              </ul>
Я не понимаю, что я должен ответить и как должно быть...

2021-10-04 16:32 UTC, Dima-Dim commented on katalog.html
> +              </ul>
Тут важно понять, есть ли проблемы с пониманием что такое списки и тем, как и где мы их используем. Если проблемы есть, то нужно прояснить этот момент. Если проблем нет, то тогда не составит сложно привести разметку к нужному виду. Я могу сказать, как именно нужно сделать, но в демке всё правильно реализовано и сделать нужно так же.
Скажи, есть ли проблемы с пониманием списков? Можешь ли ты исправить код чтобы список использовался верно?

2021-10-04 18:40 UTC, DmitryGladkikh commented on katalog.html
> +              </ul>
Не понимаю что исправить! нужны пояснения...

2021-10-05 05:09 UTC, Dima-Dim commented on katalog.html
> +              </ul>
На скрине отображено как это сейчас:
![1897183-sedona-32-pull-2](https://user-images.githubusercontent.com/35235492/135963396-e2963316-a163-417c-865e-ccfc3a673431.jpg)
одна карточка являтся списком, а всё её содержимое пунктом этого списка.
Вот ссылка на файл, где это можно так же увидеть начиная со 144-ой строки:
https://github.com/htmlacademy-htmlcss/1897183-sedona-32/blob/80802ebdb3d1ff957ed79058f2bde4ccec3f562d/katalog.html

Списком должен быть весь набор карточек, а его элементами должны быть карточки.

2021-10-05 19:22 UTC, merged