edit the code
htmlacademy-htmlcss/1897183-sedona-32 pull request #4
Opened 2021-10-19 23:49 UTC by DmitryGladkikh

2021-10-21 13:39 UTC, Dima-Dim commented on index.html
> +             <h3 class="advantages-title">настоящий<br>городок</h3>
Проблемы с отступами в разметке.

2021-10-21 13:40 UTC, Dima-Dim commented on index.html
> +            <img src="./image/photo-1.jpg" alt="Фото города Седона" width="800" height="384">
Это изображение относится к первому преимуществу.

2021-10-21 13:41 UTC, Dima-Dim commented on index.html
> +              <img src="./image/photo-2.jpg" alt="Фото Мост Дьявола" width="800" height="384">
А это, соответственно, к `там есть мост дьявола`.

2021-10-21 13:42 UTC, Dima-Dim commented on index.html
> +          <h2 class="search-title">Заинтересовались?</h2>
Проблемы с отступами в разметке, видимо, везде.

2021-10-21 13:42 UTC, Dima-Dim commented on index.html
> +        <section class="phone">
Не стоит ради одной ссылки делать section.

2021-10-21 13:44 UTC, Dima-Dim commented on styles/styles.css
> +    background-image: url("../image/background(1).jpg");
https://up.htmlacademy.ru/htmlcss/32/criteries#PROJ-02
Не нужно использовать скобки в названиях файлов и папок.

2021-10-21 21:31 UTC, DmitryGladkikh commented on index.html
> +             <h3 class="advantages-title">настоящий<br>городок</h3>
Сделал отступ как в примере

2021-10-21 21:33 UTC, DmitryGladkikh commented on index.html
> +            <img src="./image/photo-1.jpg" alt="Фото города Седона" width="800" height="384">
Не совсем понял, что исправить..

2021-10-21 21:35 UTC, DmitryGladkikh commented on index.html
> +              <img src="./image/photo-2.jpg" alt="Фото Мост Дьявола" width="800" height="384">
Проблема в названии файлов?

2021-10-29 18:43 UTC, Dima-Dim commented on index.html
>                </ul>
Если нужна техническая обёртка, то просто div.

2021-10-30 12:36 UTC, DmitryGladkikh commented on index.html
>                </ul>
Я решил не использовать в блоках с фото список

2021-10-31 17:01 UTC, Dima-Dim requested changes
https://up.htmlacademy.ru/htmlcss/32/help/4.5
"Приступать к следующему заданию по тому же проекту не стоит, пока не будет принято предыдущее. Это нужно для того, чтобы не потерялся какой-то код при работе над несколькими заданиями одновременно (возможно, это будет происходить в разных ветках), а в пулреквестах не появились конфликты."

2021-10-31 17:01 UTC, Dima-Dim commented on styles/styles.css
> +.filter-block-5 {
Не глядя в html сможешь сказать что за блок стилизует этот селектор? А через месяц сможешь? Если нет, то это плохое название.

2021-10-31 17:01 UTC, Dima-Dim commented on styles/styles.css
> +.sorting-button-3 {
Тоже самое с неймингом как и с фильтром.

2021-11-01 06:34 UTC, Dima-Dim commented
Я меня это задание числится на проверке, но я не вижу правок после своих последних комментариев, так что отправляю его на доработку, чтобы не висело в неверном статусе. Возвращай на проверку после внесения правок.

2021-11-02 15:30 UTC, DmitryGladkikh commented on katalog.html
> +                        <span class="filter-throw">Сбросить</span>
Я изменил это блок полностью. Теперь он состоит из ul li. 
Не понимаю что значит интерактивный, что я должен помень в нем?

2021-11-02 15:32 UTC, DmitryGladkikh commented on katalog.html
> +              <button class="sorting-button-1" type="image"></button>
Заменил на type button

2021-11-02 19:00 UTC, DmitryGladkikh commented on styles/styles.css
> +.filter-block-5 {
Как их назвать?

2021-11-02 19:00 UTC, DmitryGladkikh commented on styles/styles.css
> +    height: 400px;
Что здесь не так, можно пояснить?

2021-11-02 19:42 UTC, DmitryGladkikh commented on katalog.html
> +      <div class="page-footer-container">
Исправил footer

2021-11-03 06:25 UTC, Dima-Dim commented on katalog.html
> +                        <span class="filter-throw">Сбросить</span>
Комментарий оставлен к 136-ой строке в которой
`<span class="filter-throw">Сбросить</span>`
Интерактивный значит элемент с которым пользователь может взаимодействовать, нажать на него и что-то на странице изменится. Т.е. по логике он такой, а по разметке нет, потому что span это НЕ интерактивный элемент.
Что нужно сделать: разметить его как интерактивный элемент, с которым возможно взаимодействие.
Более того, для этого действия есть специальный тег со специальным типом https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type

2021-11-03 06:32 UTC, Dima-Dim commented on styles/styles.css
> +.filter-block-5 {
Так, как тебе самому в будущем будет понятно что это за селектор. Здесь нет единственного правильно ответа, есть лишь здравая логика.
Возможно для усвоения этой логики как-то поможет https://github.com/yoksel/common-words
Даже `buttons-wrapper` уже что-то.

2021-11-03 06:37 UTC, Dima-Dim commented on styles/styles.css
> +    height: 400px;
Если контента в блоке будет больше чем сейчас он "вывалится" из этого блока. Вам на лайвах рассказывали о том что вот так нужно фиксировать высоту блоков с контентом? Например блок с преимуществами Барбершопа https://up.htmlacademy.ru/htmlcss/32/demos/5465#25, перед этим была "шапка" сайта и так любой блок. Есть ли где-то для чего-то подобного фиксация высоты? Наверняка на лайвах это и голосом проговаривали.

2021-11-04 20:58 UTC, DmitryGladkikh commented on katalog.html
> +                        <span class="filter-throw">Сбросить</span>
Сделал button с type reset

2021-11-04 21:27 UTC, DmitryGladkikh commented on styles/styles.css
> +    height: 400px;
Тут я руководствовался макетом из фигмы, там есть размеры блоков width и height соответственно я их применил в разметке. Для примера я убрал сейчас height из блока search-hotel а отступ сделал с помощью margin, код выглядит вот так:

.search-hotel {
    width: 1200px;
    margin-bottom: 90px;
}
Так правильно?
Получается нужно изменить все блоки к которым я применил  height?

2021-11-04 21:31 UTC, DmitryGladkikh commented on katalog.html
> +        <section class="sorting-filter">
Речь про sorting-filter?

2021-11-05 05:28 UTC, DmitryGladkikh commented on index.html
> +          <h2 class="search-title">Заинтересовались?</h2>
Отступы поправил

2021-11-05 05:31 UTC, DmitryGladkikh commented on styles/styles.css
> +.filter-block-5 {
Я поймал небольшой ступор. Мы можем момент с неймингом отпустить на некоторое время, до завершения обучения я подумаю как их лучше назвать! Нужно двигаться вперед, а я застрял на три недели в одном месте)

2021-11-05 05:32 UTC, DmitryGladkikh commented on styles/styles.css
> +.sorting-button-3 {
То же самое, в прцессе переименую классы в которых цифры...

2021-11-05 06:59 UTC, Dima-Dim commented on katalog.html
> +        <section class="sorting-filter">
Сейчаст тут `<section class="sorting-filter">`, а был `<ul class="hotel-list">`.

2021-11-05 07:00 UTC, Dima-Dim commented on styles/styles.css
> +.filter-block-5 {
Хорошо :)

2021-11-05 07:02 UTC, Dima-Dim commented on styles/styles.css
> +    height: 400px;
Макет это статичная сущность, а мы делаем вёрстку сайта который может меняться и мы должны предусматривать эти изменения.
Ты бы внёс эти правки, опубликовал изменения и тогда было бы наверняка ясно что там у тебя получилось. В целом да, высотой ты должен управлять через отступы, обычно внутренние, т.е. padding-и, но margin тоже возможен.

2021-11-05 18:01 UTC, DmitryGladkikh commented on styles/styles.css
> +    height: 400px;
Убрал ограничение по высоте везде где это не нужно!

2021-11-05 18:19 UTC, DmitryGladkikh commented on katalog.html
> +        <section class="sorting-filter">
Сделал ul li

2021-11-06 07:45 UTC, Dima-Dim requested changes

2021-11-06 07:45 UTC, Dima-Dim commented on katalog.html
> +                <span class="control-mark"></span>
https://up.htmlacademy.ru/htmlcss/32/criteries#HTML-06

2021-11-06 07:45 UTC, Dima-Dim commented on katalog.html
> +            <button class="sorting-button-1" type="button"></button>
https://up.htmlacademy.ru/htmlcss/32/criteries#ALLY-02

2021-11-06 07:45 UTC, Dima-Dim commented on katalog.html
> +                  <img src="./image/Каталог/hotel-1.jpg" width="180" height="120" alt="Amara Resort & Spa">
https://validator.w3.org/nu/

2021-11-06 07:45 UTC, Dima-Dim commented on katalog.html
> +                <ul class="amara-resort">
Карточка является не списком, а элементом списка.

2021-11-06 07:45 UTC, Dima-Dim commented on katalog.html
> +    <img class="footer-logo" src="./image/LogoAcademy.svg" alt="Сделано в академии" width="115" height="34">
https://up.htmlacademy.ru/htmlcss/32/criteries#PROJ-03
`LogoAcademy.svg` - "Файлы и папки должны быть записаны строчными буквами ..."

2021-11-06 09:31 UTC, DmitryGladkikh commented on katalog.html
> +    <img class="footer-logo" src="./image/LogoAcademy.svg" alt="Сделано в академии" width="115" height="34">
Исправил

2021-11-06 09:31 UTC, DmitryGladkikh commented on katalog.html
> +                <ul class="amara-resort">
Исправил

2021-11-06 10:07 UTC, DmitryGladkikh commented on katalog.html
> +            <button class="sorting-button-1" type="button"></button>
Добавил всем button класс visually-hidden

2021-11-06 10:25 UTC, DmitryGladkikh commented on katalog.html
> +                  <img src="./image/Каталог/hotel-1.jpg" width="180" height="120" alt="Amara Resort & Spa">
Убрал все ошибки, кроме: 
**Внимание: В разделе отсутствует заголовок. Рассмотрите возможность использования h2-h6 элементов для добавления идентифицирующих заголовков во все разделы.
Из строки 196, столбец 15; в строку 196, столбец 42
          <section class="pagination">↩**   
Не совсем понятно как и куда добавить заголовок, visually-hidden нужно?

2021-11-06 11:09 UTC, Dima-Dim commented on katalog.html
> +            <button class="sorting-button-1" type="button"></button>
Какой смысл в кнопках которые никто не видит и на которые никто не может нажать?

2021-11-06 11:10 UTC, Dima-Dim commented on katalog.html
> +                  <img src="./image/Каталог/hotel-1.jpg" width="180" height="120" alt="Amara Resort & Spa">
Да, но возможно в таких местах и section не нужен, раз там заголовка нет. Нужно каждый такой случай смотреть отдельно.

2021-11-06 12:50 UTC, DmitryGladkikh commented on katalog.html
> +            <button class="sorting-button-1" type="button"></button>
Не правильно выразился! Описание у кнопки реализовано при помощи текста, скрытого классом visually-hidden.

2021-11-06 12:54 UTC, Dima-Dim commented on katalog.html
> +            <button class="sorting-button-1" type="button"></button>
Если так, то хорошо.

2021-11-06 12:57 UTC, DmitryGladkikh commented on katalog.html
> +                  <img src="./image/Каталог/hotel-1.jpg" width="180" height="120" alt="Amara Resort & Spa">
Все, исправил. Валидатор не показывает ошибок на всех страницах!

2021-11-06 16:16 UTC, Dima-Dim requested changes

2021-11-06 16:16 UTC, Dima-Dim commented on index.html
> +             <button class="button-twitter" type="submit"></button>
https://up.htmlacademy.ru/htmlcss/32/criteries#ALLY-02

2021-11-06 16:16 UTC, Dima-Dim commented on katalog.html
>                  <span class="control-mark"></span>
Лишний элемент всё ещё есть.

2021-11-06 16:16 UTC, Dima-Dim commented on katalog.html
> +             <span class="visually-hidden">Отображать один вариант</span>
Все эти span-ы с `visually-hidden` должны быть не рядом, а внутри кнопок.

2021-11-06 16:16 UTC, Dima-Dim commented on katalog.html
> +                <ul class="card-list">
Списком должен быть Список карточек, а каждая карточка должна быть элементом этого списка.

2021-11-06 17:29 UTC, DmitryGladkikh commented on index.html
> +             <button class="button-twitter" type="submit"></button>
Сделал в соответствии с критериями! Не понимаю что здесь не так

2021-11-06 17:30 UTC, DmitryGladkikh commented on katalog.html
>                  <span class="control-mark"></span>
Убрал

2021-11-06 17:30 UTC, DmitryGladkikh commented on katalog.html
> +             <span class="visually-hidden">Отображать один вариант</span>
Исправил

2021-11-06 17:30 UTC, DmitryGladkikh commented on katalog.html
> +                <ul class="card-list">
Переделал весь блок, так правильно?

2021-11-06 17:33 UTC, DmitryGladkikh commented on index.html
> +             <button class="button-twitter" type="submit"></button>
Вероятно type не правильный, поменял на type="button"

2021-11-06 17:34 UTC, DmitryGladkikh commented on index.html
> +             <button class="button-twitter" type="submit"></button>
Исправил

2021-11-07 09:08 UTC, DmitryGladkikh commented on katalog.html
> +                <ul class="card-list">
Так правильно?

2021-11-07 15:16 UTC, Dima-Dim commented on index.html
> +             <button class="button-twitter" type="button"></button>
Кнопка всё ещё без контента внутри.

2021-11-07 15:16 UTC, Dima-Dim commented on katalog.html
> +                <ul class="card-list">
Да.

2021-11-07 15:16 UTC, merged