Микросетка на флексах главной страницы
htmlacademy-htmlcss/1897183-sedona-32 pull request #5
Opened 2021-11-10 20:52 UTC by DmitryGladkikh

2021-11-12 07:24 UTC, Dima-Dim requested changes

2021-11-12 07:24 UTC, Dima-Dim commented on index.html
> +        <ul class="search-hotel">
Ну нет же :) Откуда тут список? Заголовок, текст, интерактивный элемент.

2021-11-12 07:24 UTC, Dima-Dim commented on index.html
> +            <br>и мы покажем вам лучшие предложения гостиниц в Седоне</p>
Шириной этот перенос регулируется.

2021-11-12 07:24 UTC, Dima-Dim commented on index.html
>              <span>поиск гостиницы в Седоне</span>
Можно и без спана обойтись.

2021-11-12 07:24 UTC, Dima-Dim commented on index.html
> +          <ul class="mailing-list">
Тут тоже нет списка.

2021-11-12 07:24 UTC, Dima-Dim commented on index.html
> +                <span>Подписаться</span>
И тоже непонятно для чего span,

2021-11-12 12:22 UTC, DmitryGladkikh commented on index.html
> +        <ul class="search-hotel">
Сделал div без списка

2021-11-12 12:28 UTC, DmitryGladkikh commented on index.html
> +            <br>и мы покажем вам лучшие предложения гостиниц в Седоне</p>
Установил ограничение по ширине для этого блока и получилось три строки, а на макете их две. Почему перенос br не подходит?

2021-11-12 12:30 UTC, DmitryGladkikh commented on index.html
>              <span>поиск гостиницы в Седоне</span>
Исправил на <p>

2021-11-12 12:30 UTC, DmitryGladkikh commented on index.html
> +                <span>Подписаться</span>
Исправил на <p>

2021-11-12 12:30 UTC, DmitryGladkikh commented on index.html
> +                <span>Подписаться</span>
<p>

2021-11-12 13:00 UTC, DmitryGladkikh commented on index.html
> +          <ul class="mailing-list">
Исправил

2021-11-13 13:17 UTC, Dima-Dim commented on index.html
> +            <br>и мы покажем вам лучшие предложения гостиниц в Седоне</p>
Потому что по макету видно именно ограничение ширины контента и br не нужен. Если текст поменяется контент менеджеру не придётся подбирать место для нового br-а.

2021-11-13 13:39 UTC, Dima-Dim reviewed
https://up.htmlacademy.ru/htmlcss/32/criteries#PROJ-02
 katalog - это не английское слово.
После того как переименуешь сделай чтобы соответствующий пункт в меню ссылался на эту страницу

2021-11-13 13:39 UTC, merged